### ISSUE TITLE
lastest module build does not work

### ISSUE THREAD

**Issue by nykez** [danielga/gm_rdb#1]
error: `[ERROR] lua/autorun/server/_rdb.lua:1: Couldn't load module library!`

Tried testing on multiple branches, and srcds32/srcds64.

**Comment by nykez** [comment]
@danielga After testing a bit more. Downloaded the pre-release builds. Switched over to x86-64 branch. The module is loaded, but calling rdb.acivate() freezes srcds. `Remote debugger output: exit status 1`

**Comment by danielga** [comment]
> The module is loaded, but calling rdb.acivate() freezes srcds.

That is normal, when you call `rdb.activate()`, the module will wait for a debugger to attach, freezing the program.

`Remote debugger output: exit status 1` This one, I'm not sure what is wrong.

**Comment by nykez** [comment]
got it working. attach config was not correct.

thanks
